name: ci-go-workflow
on: 
  pull_request:
    branches:
      - develop

jobs: 
  check-application:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-go@v2
          with:
            go-version: 1.20
        - run: go test
        - run: go run math.go

        - name: set up QEMU
          uses: docker/setup-qemu-action@v1

        - name: set up docker buildx
          uses: docker/setup-buildx-action@v1

        - name: login to dockerhub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            push: true
            tags: mateuscovos/ci-go:latest
            